<!-- resources/views/receipts/stock-report.blade.php -->
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Stock Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.5;
        }

        h1,
        h2 {
            text-align: center;
        }

        .header {
            text-align: center;
            margin-bottom: 20px;
        }

        .info {
            margin-bottom: 20px;
        }

        table {
            width: 100%;
            border-collapse: collapse;
        }

        th,
        td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: #f2f2f2;
        }

        .low-stock {
            background-color: #ffdddd;
        }

        .out-of-stock {
            background-color: #ffbbbb;
            font-weight: bold;
        }

        .summary {
            margin-top: 20px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 10px;
            color: #666;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>Stock Inventory Kasirin Report</h1>
        <p>Generated on: {{ $generatedDate }}</p>
    </div>

    <div class="info">
        <p><strong>Total Products:</strong> {{ $totalProducts }}</p>
        <p><strong>Low Stock Items:</strong> {{ $lowStockProducts }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Product Name</th>
                <th>SKU</th>
                <th>Category</th>
                <th>Current Stock</th>
                <th>Buy Price</th>
                <th>Sell Price</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($products as $product)
                <tr class="{{ $product->stock == 0 ? 'out-of-stock' : ($product->stock < 10 ? 'low-stock' : '') }}">
                    <td>{{ $product->id }}</td>
                    <td>{{ $product->name }}</td>
                    <td>{{ $product->sku ?? 'N/A' }}</td>
                    <td>{{ $product->category->name ?? 'Uncategorized' }}</td>
                    <td>{{ $product->stock }}</td>
                    <td>Rp {{ number_format($product->buy_price, 0, ',', '.') }}</td>
                    <td>Rp {{ number_format($product->sell_price, 0, ',', '.') }}</td>
                    <td>
                        @if ($product->stock == 0)
                            Out of Stock
                        @elseif ($product->stock < 10)
                            Low Stock
                        @else
                            In Stock
                        @endif
                    </td>
                </tr>
            @empty
                <tr>
                    <td colspan="8" style="text-align: center;">No products found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="summary">
        <h3>Stock Summary</h3>
        <p>
            This report shows the current stock status of all products.
            Products with stock levels below 10 are marked as "Low Stock" (highlighted in light red),
            and products with no stock are marked as "Out of Stock" (highlighted in darker red).
        </p>
    </div>

    <div class="footer">
        <p>This is an automated report generated by the inventory management system.</p>
    </div>
</body>

</html>
